main:
  bin: /usr/local/bin/rdiff-backup
  # bin: "echo"
backups:
  - name: "example"
    source: "/tmp"
    dest: "user@backupfriend.local::/backup/usb0/example"
    port: "8022"
    key: "~/.backupfriend/id_rsa"
    server_username: admin
    server_url: http://backupfriend
    every: "daily"
    time: "08:00"

